project:
  type: website
  output-dir: docs

website:
  title: "Landsat Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Landsat Analysis
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center